.retry-default: &retry-default
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

.retry:lint:
  <<: *retry-default

.retry:check-build:
  <<: *retry-default

.retry:build:
  <<: *retry-default

.retry:deploy:
  <<: *retry-default
