filebeat.inputs:
  - type: filestream
    id: filestream-logs
    encoding: utf-8
    enabled: true
    # Я запущу filebeat в докере и проброшу логи приложений по данному пути
    paths:
      - /usr/share/filebeat/logs/*.log
    parsers:
      # Определение списка парсеров, которые будут применяться к файлам логов
      - ndjson:
        # Параметр target указывает, куда будут сохранены разобранные данные.
        # Пустое значение означает, что данные будут добавлены на верхний уровень события.
        target: ""
        # Параметр message_key указывает ключ, который будет использован для извлечения сообщения из JSON-логов.
        # В данном случае ключ "msg" указывает на поле, содержащее сообщение.
        message_key: msg



output.logstash:
  # Будьте внимательны при запуске вне докера и вместо logstash укажите правильный адрес хоста с logstash.
  hosts: ["logstash:5044"]
  ssl:
    key: "config/certs/elkstack-certs/elkstack-certs.key"
    certificate: "config/certs/elkstack-certs/elkstack-certs.crt"
    certificate_authorities: ["config/certs/ca/ca.crt"]
