filebeat.inputs:
  - type: filestream
    id: filestream-logs
    encoding: utf-8
    enabled: true
    # Я запущу filebeat в докере и проброшу логи приложений по данному пути
    paths:
      - /usr/share/filebeat/logs/*.log
    parsers:
      - multiline:
          type: pattern
          # Начало нового события, если строка начинается с "{".
          pattern: '^{'
          negate: true
          match: after


output.logstash:
  # Будьте внимательны при запуске вне докера и вместо logstash укажите правильный адрес хоста с logstash.
  hosts: ["logstash:5044"]
  ssl:
    key: "config/certs/elkstack-certs/elkstack-certs.key"
    certificate: "config/certs/elkstack-certs/elkstack-certs.crt"
    certificate_authorities: ["config/certs/ca/ca.crt"]
