services:
  # region --------------- APPS -------------
  auth.api:
    container_name: auth.api
    build:
      context: ./src/apps/auth
      dockerfile: Dockerfile
    depends_on:
      - redis.db
    restart: unless-stopped

  user.api:
    container_name: user.api
    build:
      context: src/apps/users
      dockerfile: Dockerfile
#    command: ['./scripts/entrypoint.sh']
    depends_on:
      - postgres.db
    restart: unless-stopped
  # end --------------------------------------

  # region -------------- REDIS --------------
  redis.db:
    container_name: redis.db
    build:
      context: ./docker
      dockerfile: redis.Dockerfile
    restart: unless-stopped

  # end --------------------------------------

  # region --------------- DB ----------------
  postgres.db:
    image: postgres:17.2-alpine
    container_name: postgres.db
    restart: unless-stopped
  # end ---------------------------------------