services:
  # region --------------- APPS --------------
  auth.api:
    environment:
      # Redis connection configuration
      REDIS_SECURE: ${REDIS_SECURE}
      REDIS_HOST: redis.db
      REDIS_PORT: 6380
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      REDIS_DECODE_RESPONSES: ${REDIS_DECODE_RESPONSES}
      REDIS_ENCODING: ${REDIS_ENCODING}
      REDIS_POOL_MAX_CONNECTIONS: ${REDIS_POOL_MAX_CONNECTIONS}
      SSL_KEYFILE: ${SSL_KEYFILE}
      SSL_CERTFILE: ${SSL_CERTFILE}
      SSL_CERT_REQS: ${SSL_CERT_REQS}
      SSL_CA_CERTS: ${SSL_CA_CERTS}
      # Startup configuration
      PORT: ${PORT_AUTH}
      HOST: ${HOST_AUTH}
      # Pagination configuration
      PAGE_SIZE: ${PAGE_SIZE}
      # Auth configuration
      TOKEN_URL: ${TOKEN_URL}
      USER_ENDPOINT_URL: ${USER_ENDPOINT_URL}
      PRIVATE_KEY_PATH: ${PRIVATE_KEY_PATH}
      PUBLIC_KEY_PATH: ${PUBLIC_KEY_PATH}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${REFRESH_TOKEN_EXPIRE_MINUTES}
      # Other
      CLIENT_ID: ${CLIENT_ID_AUTH}
      CLIENT_SECRET: ${CLIENT_SECRET_AUTH}
      OPENAPI_URL: ${OPENAPI_URL_AUTH}
      TZ: Europe/Moscow
    volumes:
      - online_logs:/usr/src/app/logs
      - redis_certs:/usr/src/app/redis/certs
    ports:
      - "1500:80"

  user.api:
    environment:
      # Postgres connection configuration
      PG_HOST: postgres.db
      PG_PORT: 5432
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE_USER}
      # Startup configuration
      PORT: ${PORT_USER}
      HOST: ${HOST_USER}
      # Pagination configuration
      PAGE_SIZE: ${PAGE_SIZE}
      # Auth configuration
      TOKEN_URL: ${TOKEN_URL}

      AUTH_ENDPOINT_URL: ${AUTH_ENDPOINT_URL}
      AUTH_URL: ${AUTH_URL}
      # Other
      CLIENT_ID: ${CLIENT_ID_USER}
      CLIENT_SECRET: ${CLIENT_SECRET_USER}
      OPENAPI_URL: ${OPENAPI_URL_USER}
      TZ: Europe/Moscow
    volumes:
      - online_logs:/usr/src/app/logs
    ports:
      - "1000:80"

  # end ---------------------------------------

  redis.db:
    environment:
      REDIS_ARGS: "user my_redis on >online_redis ~* +@all"
      TZ: Europe/Moscow
    ports:
      - "6379:6379"
      - "6380:6380"  # Порт для SSL
    privileged: true
    volumes:
      - redis_certs:/certs
      - redis_data:/data/
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/users.acl:/usr/local/etc/redis/users.acl


  # region --------------- DB ----------------
  postgres.db:
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - "54330:5432"
    volumes:
      - ./docker/scripts/db-initializer.sh:/docker-entrypoint-initdb.d/db-initializer.sh
      - postgres_data:/var/lib/postgresql/data/
  # end ---------------------------------------

volumes:
  online_logs:
    name: online_logs
  redis_certs:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local