version: "3.11"

services:
  # region --------------- APPS --------------
  auth.api:
    container_name: auth.api
    build:
      context: ./src/apps/auth
      dockerfile: Dockerfile
    depends_on:
      - postgres.db
    restart: always

  user.api:
    container_name: user.api
    build:
      context: src/apps/users
      dockerfile: Dockerfile
    depends_on:
      - postgres.db
    restart: always
  # end ---------------------------------------

  # region --------------- DB ----------------
  postgres.db:
    image: postgres:14.6-alpine
    container_name: postgres.db
    restart: always
 # end ---------------------------------------