"""Init

Revision ID: 69b84f27d4dc
Revises: e85b4bc34a45
Create Date: 2024-09-03 15:41:47.508831

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '69b84f27d4dc'
down_revision: Union[str, None] = 'e85b4bc34a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_role_id'), 'role', ['id'])
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_role_id'), 'role', type_='unique')
    # ### end Alembic commands ###
