version: 1
disable_existing_loggers: False

formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "%(asctime)s - %(levelname)s - %(message)s"
    use_colors: null

  access:
    "()": uvicorn.logging.AccessFormatter
    fmt: '%(asctime)s - %(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'

  json_formatter:
    (): core.logger.JSONFormatter

filters:
  message_filter:
    "()": core.logger.LoggingFilter

handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr

  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout

  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json_formatter
    filename: logs/app.log
    mode: a
    encoding: utf8
    filters:
      - message_filter

loggers:
  uvicorn:
    handlers:
      - default
      - file
    level: INFO
    propagate: False

  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers:
      - access
      - file
    level: INFO
    propagate: False

  root:
    handlers:
      - console
      - file
    level: INFO
    propagate: False
