"""Initial revision

Revision ID: b3807c4f5200
Revises: 
Create Date: 2024-08-14 07:33:52.722477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3807c4f5200'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoleDB',
    sa.Column('Name', sa.String(length=256), nullable=True),
    sa.Column('Role', sa.Integer(), nullable=False),
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('UserDB',
    sa.Column('UserName', sa.String(length=100), nullable=True),
    sa.Column('LastName', sa.String(length=100), nullable=True),
    sa.Column('FirstName', sa.String(length=100), nullable=True),
    sa.Column('SecondName', sa.String(length=100), nullable=True),
    sa.Column('FullName', sa.String(length=200), nullable=True),
    sa.Column('Email', sa.String(length=256), nullable=True),
    sa.Column('PasswordHash', sa.LargeBinary(), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=18), nullable=True),
    sa.Column('Photo', sa.String(length=100), nullable=True),
    sa.Column('Birthday', sa.DateTime(), nullable=True),
    sa.Column('LoggedOut', sa.Boolean(), nullable=False),
    sa.Column('Deleted', sa.Boolean(), nullable=False),
    sa.Column('IsMan', sa.Boolean(), nullable=False),
    sa.Column('RoleId', sa.UUID(), nullable=True),
    sa.Column('DateAdd', sa.DateTime(), nullable=False),
    sa.Column('DateUpdate', sa.DateTime(), nullable=False),
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['RoleId'], ['RoleDB.Id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserDB')
    op.drop_table('RoleDB')
    # ### end Alembic commands ###
